### ISSUE TITLE
Disable garbage collection for simple program?

### ISSUE THREAD

**Issue by dg1727** [shedskin/shedskin#241]
I'm thinking of using Shedskin for a very simple program which does some simple command-line parsing & copies some strings from the command line to a file.  The program also needs to exec() another program (I'm using generic terminology, not Python nor C++).  

The program is part of an add-on for use with Git.  I don't want this add-on to have any dependencies other than what Git has.  Git depends on libpcre3 but not libgc (package "libgc1c2" in Debian-based Linux).  

I think that my program, being very simple, doesn't need garbage collection.  Is there a straightforward way to have a Shedskin-compiled program not depend on libgc?

**Comment by dg1727** [comment]
My program also needs to read & set the PATH environment variable.  

There is some string concatenation etc., but none of this is (for example) in a loop that may iterate many times.  The total amount of string operations is small enough that I don't think garbage collection is really needed.

**Comment by Arkanosis** [comment]
There's nothing built in to disable garbage collection as it would lead to significant leaks in most cases, but if you're fine with leaking a few bytes before an `exec()`, I guess you could get what you want by:
- redefining `__GC_STRING`, `__GC_DEQUE` and `__GC_VECTOR` to `std::string`, `std::deque` and `std::vector`, respectively, in shedskin/lib/builtin.hpp;
- using `malloc` and `free` instead of `GC_MALLOC*` and `GC_FREE*`, respectively, everywhere;
- removing the `#include` for Boehm GC and not linking against it.

**Comment by srepmub** [comment]
added a -c/--nogc option.

might be fun to also control the gc via 'import gc; gc.enable/disable()'

**Comment by srepmub** [comment]
gc module now partly supported: enable, disable, collect. in addition to the -c/--nogc option.
