### ISSUE TITLE
Project contribution statistics somewhat skewed

### ISSUE THREAD

**Issue by pfalcon** [shedskin/shedskin#247]
As a short intro, anyone who would seriously consider using some open-source project from Github, without even speaking about contribution, would probably go to contribution stats page, to see who's who in the project and how it is active overall: https://github.com/shedskin/shedskin/graphs/contributors .

And what can be seen for Shedskin is that top 2 contributors have 34 and 33 commits each respectively. At the same time, a look at https://github.com/shedskin/shedskin shows that totally, project has "2,664 commits".

All that leaves that feeling of exinanition and unmaintainence, and unlikely motivates to contribute.

Can something please be done about it? Of course, the main author of Shedskin is Mark Dufour:

~~~
$ git log | grep Author: | grep -i Dufour | wc
   2479    8562  145179
~~~

So, the issue is that his commits aren't attributed to him. Obvious reason would be that he simply doesn't have a github account. But with a bit of detective work, @srepmub appears to be him after all (same nick used in http://shed-skin.blogspot.com/ , in https://groups.google.com/forum/#!topic/shedskin-discuss/sAYBS0kMVsI). Mark, is that you? Would you be interested to get your credit from Github stats system and make this project look less a vacant place? Thanks in advance!

**Comment by Arkanosis** [comment]
Yeah, you're correct on all counts.

Let's make one simple thing clear first: @srepmub is Mark without any doubt, and he's been part of the @shedskin organization since [we've migrated Shed Skin from Google Code to GitHub](https://groups.google.com/forum/#!topic/shedskin-discuss/sAYBS0kMVsI) in 2015.

I assume he's not visible in the contributors list on GitHub because the emails he used while working on Shed Skin aren't linked to his GitHub account. @tomspur commited a `.mailmap` to fix the same issue in some tools (eg. `tig`), but I'm afraid only Mark could fix it on GitHub (and even that, I'm not 100% sure, as GitHub would probably require that he's still in control of all the email addresses he's used in the past).

The same issue most likely impacts other contributors as well. Also, I believe Mark originally committed third-party contributions himself (with proper credit in the commit message), because the tools used at the time (SVN) didn't implement merge requests. That's something we have to deal with, I guess.

Thanks!

**Comment by pfalcon** [comment]
@Arkanosis: Thanks for the prompt response! It's great to see that even though there may be not active development, the maintenance is active. The thread you link to shows that the migration was handled in the top-notch manner, thanks!

So, I hope there might be still some interest/energy to fix up such "last mile" issues, and Mark will respond.

> but I'm afraid only Mark could fix it on GitHub (and even that, I'm not 100% sure, as GitHub would probably require that he's still in control of all the email addresses he's used in the past).

Right, I used to have a similar problem, and it involves adding aliases for email addresses used in commits, via account settings. By now I don't remember either if there was a confirmation required for addresses added or not. Anyway, I don't rush to provide step by step instructions right away, but if Mark responds, and if such instructions are useful, I'd be glad to look them up. Thanks!

**Comment by srepmub** [comment]
hi guys,

> @Arkanosis <https://github.com/Arkanosis>: Thanks for the prompt response!
> It's great to see that even though there may be not active development, the
> maintenance is active. The thread you link to shows that the migration was
> handled in the top-notch manner, thanks!

yes, thanks from my side too! :) it's awesome to see some work continue on shedskin, even if it's only maintenance-type stuff!

I added my gmail address to my github account, and now the stats seem to be fixed (even though I'm pretty sure I never added 5 million lines? :P).

minor personal update, if anyone is interested: I forked myself twice about 5 years ago, developed some new hobbies, became vegan with wife & kids about 4 years ago, and started working at an open source company also 5 years ago.. turns out it was really hard to continue work on shedskin in these conditions, also without much feedback..

at the time I considered it as a useful demonstrator that such a thing can be done at all, and it basically does everything I set out to do. I have several ideas which would make type analysis scale a lot better, but it's probably too late now to make such large changes. somebody please continue my work in the form of a PhD.. :-) (I toyed with that idea for myself, but I don't think it will happen.)


thanks again!!
mark.

**Comment by pfalcon** [comment]
> I added my gmail address to my github account, and now the stats seem to be fixed

Great, thanks! Indeed, ~1K commits are recovered, but it still would be interesting to see if it's possible to recover remaining ~1.4K. @Arkanosis mentioned there's a git mailmap, and I believe I heard Github can make use of it. So, all in all, I would be interested to look into that (and hopefully will find time), so propose not to close this ticket yet.

> minor personal update, if anyone is interested:

Sure, it's quite understandable that interests and life circumstances change. I however starting to look what happens after all that still. Some guy recently contacted me about a program I've written as a term project at university. That was 20 years ago. Obviously, I don't have it now, and it's rather useless, but somebody wanted to have a look.

So, we (as a Python community) can't allow to happen to Shedskin what happened to starkiller or pyvm. And well, it doesn't happen. But yet better would be to port it up Python3, to show that we as a community have continuity, instead of morbid split over Python2 vs Python3, and that we always had, and keep having, advanced tools, not worse than new buzzword languages popping around.

And of course, Shedskin is an implementation of a cool advanced algorithm, which is a eternal value in itself, without recurse to boring practical applied needs ;-).

So, all in all, if maintainers will keep around and are responsive with reviews and merges, I'm sure Shedskin will keep its position among advanced language tools!

Thanks again for all the work put into it!

**Comment by pfalcon** [comment]
@srepmub, Ah, and if you're listening, please let me bother you with another small request:

> @srepmub is Mark without any doubt, and he's been part of the @shedskin organization since [we've migrated Shed Skin from Google Code to GitHub](https://groups.google.com/forum/#!topic/shedskin-discuss/sAYBS0kMVsI) in 2015.

But your membership in the "shedskin" github organization is not visible, because it's apparently set as "Private". Dunno why Github sets membership visibility as "Private" by default for open-source projects, apparently it's very concerned with privacy ;-).

Would you consider making it public, so people coming by again had an easy way to know who's who in the project? You can do that on this page: https://github.com/orgs/shedskin/people (which is itself reachable from https://github.com/shedskin). There, you should be able to see static Public/Private labels for other people, but for yourself it's actually a dropbox where it can be changed.

The migration post on the mailing list also mentioned:

> So, I've created a “shedskin” organization there, and set Mark,
Fahrzin and Thomas as owners.

But likewise, @fahhem is not visible in public members. I'm sorry again if it's just changes in project membership, but if not, maybe you'll be interested to make it public too?


And of course, that's just a suggestion. The distinction of public/private membership can be that of active/inactive project member. But in all fairness, I don't understand why someone would participate in an open-source project and then hide it. Suppose as a next twist, you'll want to go and work for Apple on LLVM. When they'll see that you hacked advanced program analysis algorithms yet in 2008, they'll grab you out ;-).

**Comment by fahhem** [comment]
Thanks for pointing this out! I didn't know I wasn't visible in the People
page, though I should say I haven't been active in a long time anyway.

I can't wait for the recruitment emails that say they like my work in
shedskin and how it's relevant to their mobile app! ;)

**Comment by srepmub** [comment]
no I'm not chaotic at all:

Author: mark.dufour <mark.dufour@acccb5f4-fd3f-0410-a51f-a7a3fbc0418d>
Author: mark dufour <mark.dufour@gmail.com>
Author: Mark Dufour <mark.dufour@gmail.com>
Author: Mark Dufour <m.dufour@knmp.nl>
Author: srepmub <m.dufour@kopano.com>
Author: srepmub <srepmub@akemi.(none)>
Author: srepmub <srepmub@ouvrage.(none)>

would anyone oppose it if I were to rewrite history a bit to clean this up?

**Comment by pfalcon** [comment]
> no I'm not chaotic at all:

Well, if development done over long time (== different machines), that's not unexpected ;-).

> would anyone oppose it if I were to rewrite history a bit to clean this up?

I'm just a passer-by, but if an option like that is considered, I'd say it's a good way to cut a gordian knot like that. I guess who'd have a say on that are distro package maintainers. But if a change like that is accompanied with tagging a new release (and changes in master if small, but IMHO pretty worth a point release), I hope there shouldn't be too strong an opposition.

**Comment by srepmub** [comment]
thanks! ^^ I just rewrote the authors. we'll deal with distro maintainers when they still want to package/upgrade shedskin at some point.. :P I wouldn't expect many problems there..

**Comment by pfalcon** [comment]
> I just rewrote the authors.

Thanks for going forward with cleaning up this! The stats are now fully ok, so this ticket is resolved.

**Comment by pfalcon** [comment]
P.S. Thanks for the follow up stream of code maintenance commits! :+1:
