### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by xyproto** [shedskin/shedskin#264]
Hi,

I'm trying to package Shedskin for Arch Linux, for Python 3. (Python 3.8.1).

I used this bash snippet for replacing integers with leading zeros to octal numbers:

```bash
for i in $(seq 0 9); do
  sed -i "s,=0$i,=0o$i,g;s, 0$i, 0o$i,g" "$pkgname/shedskin/lib/"{stat.py,os/__init__.py}
done
```

I used the latest commit on master, since (as far as I could tell), there are no release tag with support for Python 3 yet.

Building and installation went fine, but when running `shedskin`, I get this:

```
% shedskin
Traceback (most recent call last):
  File "/usr/bin/shedskin", line 2, in <module>
    import shedskin
  File "/usr/lib/python3.8/site-packages/shedskin/__init__.py", line 16, in <module>
    import graph
ModuleNotFoundError: No module named 'graph'
```

Here is the `PKGBUILD` file I'm working on:

```bash
pkgname=shedskin
pkgver=0.9.4_py3
pkgrel=1
pkgdesc='Python to C++ compiler'
arch=(any)
url='https://shedskin.github.io/'
license=(GPL2)
depends=(pcre gc python python-blessings python-jinja python-progressbar python-six)
makedepends=(git)
source=("git+https://github.com/shedskin/shedskin.git#commit=ae88dbca7b1d9671cd8be448cb0b497122758936")
sha256sums=('SKIP')

prepare() {
  # Correct the path to the python interpreter
  sed -i 's,bin/python,usr/bin/python,' "$pkgname/scripts/$pkgname"
  # Python 3 does not permit leading zeros for integers, this changes them to octal numbers
  for i in $(seq 0 9); do
    sed -i "s,=0$i,=0o$i,g;s, 0$i, 0o$i,g" "$pkgname/shedskin/lib/"{stat.py,os/__init__.py}
  done
}

package() {
  cd "$pkgname"
  python setup.py install --root="$pkgdir" --optimize=1
}
```

I am just prematurely trying to package Shedskin for Python 3, or is there something I have overlooked?

Any ideas, tips or tricks are welcome.

Thanks for developing shedskin.

Best regards,
Alexander F. Rødseth

**Comment by pfalcon** [comment]
> or is there something I have overlooked?

Perhaps https://github.com/shedskin/shedskin/pull/242, https://github.com/shedskin/shedskin/pull/261, and https://github.com/shedskin/shedskin/pull/262, aka all currently open pull requests?

**Comment by xyproto** [comment]
@pfalcon This looks like great progress towards Shedskin using Python 3. What would you advice me to do? Just wait for the next release tag? All Arch Linux packes ar being moved away from Python 2 now, as long as it is possible to do so. Thanks.

**Comment by pfalcon** [comment]
@xyproto: I can only suggest what I would do (actually, what is in my queue for a while): https://github.com/shedskin/shedskin/pull/261 is the most important patch on Python3 upgrade path (I mean, real upgrade, where Shedskin not just runs on Python3, but compiles Python2, but moves towards compiling Python3), so I would ping author of that patch if they're still interested in working on that, help with review, etc.

Then politely ping @srepmub, @tomspur, and other maintainers who are still reachable asking for a motion on these matters, assuming that patches are in good shape. Because the situation is that Shedskin isn't really actively maintained, which is a shame of course. I'm among the folks who'd like to help, but work on tons of projects, so can't work on everything at once.

If you're shooting to just being able to run on Python3, instead of complete code modernization for it, then it may be easier task within reach - just produce clean patches for this, and be long enough to ensure they're merged.

**Comment by xyproto** [comment]
Yes, just running with Python 3 would be enough to tick the box for having transitioned the Arch Linux package from 2 to 3.

Thanks for the pointers!

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/ supports python3.

**Comment by xyproto** [comment]
shedskin has been in AUR since 2020-01-18
