### ISSUE TITLE
the use of compiler

### ISSUE THREAD

**Issue by littleyellowfishes** [shedskin/shedskin#269]
Hi, Can I ask what is compiler.ast that been use? I didn't find this library and didn't see a compiler file in this project.

**Comment by Arkanosis** [comment]
Hello @littleyellowfishes 

[compiler](https://docs.python.org/2/library/compiler.html) is a Python 2 module that has been deprecated since Python 2.6 and removed from Python 3. Indeed, while there have been some efforts to port shedskin to Python 3, the latest release still is for Python 2.

Should one want to find the same features in Python 3, the [ast](https://docs.python.org/3.10/library/ast.html) module should do it.

For more insights about this, please read @pfalcon 's comment [on this pull request](https://github.com/shedskin/shedskin/pull/242#issuecomment-460059024).

**Comment by littleyellowfishes** [comment]
> Hello @littleyellowfishes
> 
> [compiler](https://docs.python.org/2/library/compiler.html) is a Python 2 module that has been deprecated since Python 2.6 and removed from Python 3. Indeed, while there have been some efforts to port shedskin to Python 3, the latest release still is for Python 2.
> 
> Should one want to find the same features in Python 3, the [ast](https://docs.python.org/3.10/library/ast.html) module should do it.
> 
> For more insights about this, please read @pfalcon 's comment [on this pull request](https://github.com/shedskin/shedskin/pull/242#issuecomment-460059024).

Woah thank you for the fast reply, I see it now. tyty
