### ISSUE TITLE
walrus operator inside list comprehension

### ISSUE THREAD

**Issue by srepmub** [shedskin/shedskin#371]
currently not working:

```
total = 0
partial_sums = [total := total + v for v in range(5)]
print(total)
```

guessing this is because scoping rules have changed over time. not even sure if list comprehensions have their own scope anymore.. need to investigate..

**Comment by srepmub** [comment]
or perhaps it's just the walrus assignment here that throws a wrench into things.

**Comment by srepmub** [comment]
as of python3 I think, variables 'defined' in list comprehensions do not 'leak' out of list comprehension scopes anymore  (they did so in python2 , at least in some cases). but I think this was always implemented in shedskin like this so that actually solved itself.. 

but for the walrus operator I guess we need to define the variable in the parent scope. and it seems the walrus operator can only be used in an 'outer' list comprehension (that is, when you start nesting list comprehensions)..

so this would require a few extra checks and passing a reference to 'total' to the outer list comprehension (if 'total' is not a global variable).

**Comment by humhue** [comment]
Is the prototype of the function `list_comp_0` (`static inline list<__ss_int> *list_comp_0();`) there for a reason?

**Comment by srepmub** [comment]
in C/C++, it's normal to declare everything before doing anything. so for example some other list comprehension can use list_comp_0 before it is actually defined.

in this simple case the declaration may not be needed, but often it's not worth the effort to try and be smarter about generated code.

**Comment by humhue** [comment]
https://github.com/humhue/shedskin/commit/2fe33018c7742db5a3bd5e4a102af44a24eadeac

The rationale here is that we _hardly_ ever want variables inside list comprehensions.
It fixes the issue, but it's quite hacky and it comes with a gotcha:
```
v = 0
total = 0
partial_sums = [total := total + v for v in range(5)]
print(v)
```
(this happens with every list comprehension, if `i`/`v` were previously declared in a global scope; there shouldn't be any code depending on this anyway)
this will print 0 in CPython and Shed Skin, 4 with that commit, at the same time though, in the latest Shed Skin `total` and `partial_sums` won't have the right values, since `total` doesn't get initialized.
This issue can also be fixed by editing graph.py, but I've not had the time yet to figure how to do that properly.

**Comment by srepmub** [comment]
thanks, nice try, but it doesn't work when you put this in a function.. ;-) (since 'total' is not a global variable anymore, we cannot access it from inside the l.c.).

**Comment by srepmub** [comment]
went ahead and fixed this, using pass-by-reference for target variables so they can be modified from inside list comprehensions.
