### ISSUE TITLE
Lack of documentation for code structure

### ISSUE THREAD

**Issue by anirudha-commits** [shedskin/shedskin#512]
The repo lacks a documentation explaining flow for commands i.e. `translate`, `build`, `analyze` etc. It would be great if someone could add high level documentation for important classes and the way they are connected. Some sort of blog or a video explaining the code-base could potentially attract more contributors without large context.

**Comment by srepmub** [comment]
thanks for the suggestion. I think it would first be nice to try and make things more self-evident. for example, shedskin -h now gives: 

```
$ shedskin -h
usage: shedskin [-h] {analyze,translate,build,run,test} ...

Restricted-Python-to-C++ Compiler

options:
  -h, --help            show this help message and exit

subcommands:
  {analyze,translate,build,run,test}
    analyze             analyze and validate python module
    translate           translate python module to cpp
    build               build translated module
    run                 run built and translated module
```

most importantly perhaps, we could make it clear that 'translate' uses a Makefile, and the rest CMake. btw, the analyze command seems to not do anything at the moment.

**Comment by srepmub** [comment]
also 'shedskin run -h' gives a list of options that are not applicable.

**Comment by shakfu** [comment]
@anirudha-commits / @srepmub 

Couldn't agree more with the comment that we need better documentation of command-line options, of docstrings in general, and of the programmatic api in shedskin.

I would love to have a simpler command line interface myself, but this work is always iterative and requires a conversation about which options are better exposed at the command line or the programmatic side.

With respect to the command line api it is clear that we erred on the side of exposing as many options as possible, but this, of course, makes the api less approachable and more confusing to newcomers. 

In any case, the recent huge effort by Mark to add type annotations to the code base is a big step towards improving shedskin's docs.

At least for me, this will likely be an area of focus over the next phase of development. Needless to say code contributions, refactoring suggestions and feedback like this are always welcome.

**Comment by anirudha-commits** [comment]
Thanks for the comments!
I am more interested about the design decisions. Let us say about the hierarchy of the generated C++ file. What will be the namespace? What content goes in header file? How do you handle inheritance? What about virtual functions? 

I meant more of a high level documentation/video/presentation explaining what file does what or structure of generated file. Ofc I will read the code eventually but initial delta seemed to be too high to even start. I found your msc thesis online which may not be relevant now: https://web.archive.org/web/20061213130453/http://mark.dufour.googlepages.com/shedskin.pdf

I am really appreciating your efforts after reading the code.

**Comment by srepmub** [comment]
I just filled in a few docstrings (shedskin/virtual.py and shedskin/extmod.py), improved the command-line option descriptions and fixed 'shedskin analyze'.. at least it should be clearer now how we handle 'virtual' calls. thanks for triggering!

in general, we try to make use of existing C++/STL features where possible. so inheritance in Python becomes inheritance in C++, exceptions become C++ exceptions, lists become (wrapped) STL vectors, virtual functions become virtual functions and so on.. in a way, shedskin provides python syntax for writing C++ code, if that makes sense.. :P

I think in this sense, my MsC thesis is still valid, although I have scaled down the ambitions a bit over time.. :) for example we don't even try to generate 'generic' types anymore.

I'm not sure if I would want to write a technical overview separate from the docstrings, but I'm happy to try and answer any questions you may have and see if we can make the answer more evident from the code base/docstrings themselves..

**Comment by anirudha-commits** [comment]
what does `infer.py` do? Will code generation work if we remove `infer.analyze()`?

**Comment by shakfu** [comment]
@anirudha-commits 

> what does `infer.py` do? Will code generation work if we remove `infer.analyze()`?

Direct experimentation with shedskin codebase is welcome. My favorite method is to insert `from IPython import embed; embed()` in the code and then poke around the variables given different python conversion targets.

**Comment by srepmub** [comment]
the explanation in the top of infer.py is probably a bit too technical. I will add a bit of introductory text shortly.

**Comment by srepmub** [comment]
I _think_ I managed to improve the infer.py docstring.

**Comment by srepmub** [comment]
any thing else we could improve on the documentation side..?

**Comment by shakfu** [comment]
Will have another look again... It was all very fast last time.

**Comment by shakfu** [comment]
> I _think_ I managed to improve the infer.py docstring.

How about the following additional clarification:

`shedskin.infer`: infer types

Type inference in Shed Skin works by propagating types along a constraint graph.
The graph is built during the analysis phase in `shedskin.graph`.

The inference starts from known type "seeds" - for example, when a variable 'x'
is assigned a literal integer value like '0', that integer type propagates to
everywhere 'x' is used.

A key challenge is handling cases where types flow together and mix. This happens in scenarios like:
- An identity function called with different argument types, leading to an
  imprecise return type.
- Lists containing elements of different types.

To maintain precision, Shed Skin duplicates parts of the constraint graph during
analysis. This allows different uses of functions (parametric polymorphism) and
containers (data polymorphism) to be analyzed separately.

The implementation combines two key algorithms:

1. Agesen's Cartesian Product Algorithm (CPA) for handling function polymorphism, where the return type of a method may depend on the actual types of the method arguments.

2. Plevyak's Iterative Flow Analysis (IFA) for handling data polymorphism, where the type of a variable may depend on the control flow.

The analysis proceeds in phases:

FORWARD PHASE
- Propagate types through the constraint graph via `propagate()`
- Create function duplicates using CPA via `cpa()`
- Seed allocation points with correct types via `ifa_seed_template()`

BACKWARD PHASE
- Find imprecision points and determine classes to duplicate via `ifa()`
- Trace backwards through graph to find related allocation points
- Duplicate classes and distribute them across allocation points

CLEANUP
- Exit if no imprecision points found
- Otherwise reset graph and restart analysis
- Maintain allocation point types in `gx.alloc_info`

The analysis runs incrementally, analyzing a limited set of functions and
allocation sites before re-running. This helps prevent CPA explosion early
in the process.

For more details, see:
- Ole Agesen's PhD thesis on the CPA algorithm
- Mark Dufour's MSc thesis on Shed Skin's implementation

**Comment by shakfu** [comment]
> looks good! I guess you removed this
> 
> "The two integers mentioned in the graph.py description are used to keep track of duplicates along both dimensions (class duplicate, function duplicate)."
> 
> since it's also explained in graph.py?

It was an omission which I will correct as follows:

In `graph.py`, I will change the reference to the integers:

```text
Nodes are identified by an AST Node, and two integers. The integers are
used in `infer.py` to duplicate parts of the constraint graph along two 
dimensions (class duplicate, function duplicate).
In the initial constraint graph, these integers are always 0.
```

In the `infer.py` doc string, I will include this:

```
In each node of `shedskin.graph`, two integers are used by `shedskin.infer` 
to duplicate parts of the constraint graph along two  dimensions (class 
duplicate, function duplicate). Refer to the doctoring of the former for 
more information.
```

**Comment by srepmub** [comment]
doctoring -> docstring :)

**Comment by srepmub** [comment]
enough improvements I would say in this area.
